class ScheduleData {
  static Map<String, Map<String, List<Map<String, String>>>> schedule = {
    "Saturday": {
      "4th Year Even Sem": [
        {"time": "8.00 am", "sub": "CSE 4207", "sec": "A", "teacher": "NS", "room": "201"},
        {"time": "8.50 am", "sub": "CSE 4203", "sec": "A", "teacher": "RT", "room": "201"},
        {"time": "9.40 am", "sub": "CSE 4201", "sec": "A", "teacher": "SA", "room": "201"},
        {"time": "10.50 am", "sub": "CSE 4204", "sec": "A", "teacher": "RT", "room": "HPCl"},
        {"time": "11.40 am", "sub": "CSE 4204", "sec": "A", "teacher": "RT", "room": "HPCl"},
        {"time": "12.30 pm", "sub": "CSE 4204", "sec": "A", "teacher": "RT", "room": "HPCl"},
        {"time": "10.50 am", "sub": "CSE 4202", "sec": "B", "teacher": "MSH", "room": "PG Lab"},        
        {"time": "11.40 am", "sub": "CSE 4202", "sec": "B", "teacher": "MSH", "room": "PG Lab"},
        {"time": "12.30 pm", "sub": "CSE 4202", "sec": "B", "teacher": "MSH", "room": "PG Lab"}, 
        {"time": "2.30 pm", "sub": "CSE 4203", "sec": "B", "teacher": "MIT", "room": "201"},
        {"time": "3.20 pm", "sub": "CSE 4201", "sec": "B", "teacher": "MSH", "room": "201"},
        {"time": "4.10 pm", "sub": "CSE 4207", "sec": "B", "teacher": "FAR", "room": "201"},
        {"time": "8.00 am", "sub": "CSE 4201", "sec": "C", "teacher": "SA", "room": "202"},
        {"time": "8.50 am", "sub": "CSE 4201", "sec": "C", "teacher": "SA", "room": "202"},
        {"time": "9.40 am", "sub": "CSE 4203", "sec": "C", "teacher": "MIT", "room": "202"},        
      ],
      "3rd Year Even Sem": [
        {"time": "8.50 am", "sub": "CSE 3207", "sec": "A", "teacher": "MAN", "room": "203"},
        {"time": "9.40 am", "sub": "CSE 3205", "sec": "A", "teacher": "EKH", "room": "203"},
        {"time": "10.50 am", "sub": "CSE 3209", "sec": "A", "teacher": "MFF", "room": "201"},
        {"time": "8.00 am", "sub": "CSE 3202", "sec": "B", "teacher": "FAR", "room": "NW Lab"},
        {"time": "8.50 am", "sub": "CSE 3202", "sec": "B", "teacher": "FAR", "room": "NW Lab"},
        {"time": "9.40 am", "sub": "CSE 3202", "sec": "B", "teacher": "FAR", "room": "NW Lab"},
        {"time": "10.50 am", "sub": "CSE 3206", "sec": "B", "teacher": "EKH", "room": "ACL"},
        {"time": "11.40 am", "sub": "CSE 3206", "sec": "B", "teacher": "EKH", "room": "ACL"},
        {"time": "12.30 pm", "sub": "CSE 3206", "sec": "B", "teacher": "EKH", "room": "ACL"},
        {"time": "2.30 pm", "sub": "CSE 3205", "sec": "B", "teacher": "FP", "room": "102"},
        {"time": "3.20 pm", "sub": "CSE 3209", "sec": "B", "teacher": "MIT", "room": "102"},
        {"time": "4.10 pm", "sub": "CSE 3203", "sec": "B", "teacher": "HsN", "room": "102"},
        {"time": "11.40 am", "sub": "CSE 3209", "sec": "C", "teacher": "MFF", "room": "101"},
        {"time": "12.30 pm", "sub": "CSE 3201", "sec": "C", "teacher": "NS", "room": "101"},
        {"time": "2.30 pm", "sub": "CSE 3208", "sec": "C", "teacher": "NOS", "room": "HPCL"},
        {"time": "3.20 pm", "sub": "CSE 3208", "sec": "C", "teacher": "NOS", "room": "HPCL"},
        {"time": "4.10 pm", "sub": "CSE 3208", "sec": "C", "teacher": "NOS", "room": "HPCL"},
      ],
       "3rd Year Odd Sem": [
        {"time": "8.00 am", "sub": "CSE 3109", "sec": "A", "teacher": "MAN", "room": "103"},
        {"time": "8.50 am", "sub": "CSE 3101", "sec": "A", "teacher": "AYS", "room": "103"},
        {"time": "9.40 am", "sub": "CSE 3105", "sec": "A", "teacher": "NS", "room": "103"},
        {"time": "10.50 am", "sub": "CSE 3101", "sec": "A", "teacher": "AYS", "room": "101"},
        {"time": "8.00 am", "sub": "CSE 3107", "sec": "B", "teacher": "UD", "room": "102"},
        {"time": "8.50 am", "sub": "CSE 3105", "sec": "B", "teacher": "NS", "room": "102"},
        {"time": "9.40 am", "sub": "CSE 3109", "sec": "B", "teacher": "AMR", "room": "102"},
        {"time": "9.40 am", "sub": "CSE 3107", "sec": "C", "teacher": "FP", "room": "202"},
        {"time": "10.50 am", "sub": "CSE 3101", "sec": "C", "teacher": "SeN", "room": "102"},
        {"time": "11.40 am", "sub": "CSE 3101", "sec": "C", "teacher": "SeN", "room": "102"},
        {"time": "12.30 pm", "sub": "CSE 3105", "sec": "C", "teacher": "NOS", "room": "102"},
        {"time": "2.30 pm", "sub": "CSE 3102", "sec": "C", "teacher": "SeN", "room": "PG Lab"},
        {"time": "3.20 pm", "sub": "CSE 3102", "sec": "C", "teacher": "SeN", "room": "PG Lab"},
        {"time": "4.10 pm", "sub": "CSE 3102", "sec": "C", "teacher": "SeN", "room": "PG Lab"},
      ],
       "2nd Year Odd Sem": [
        {"time": "8.00 am", "sub": "CSE 2104", "sec": "A", "teacher": "BA", "room": "HW Lab"},
        {"time": "8.50 am", "sub": "CSE 2104", "sec": "A", "teacher": "BA", "room": "HW Lab"},
        {"time": "9.40 am", "sub": "CSE 2104", "sec": "A", "teacher": "BA", "room": "HW Lab"},
        {"time": "8.00 am", "sub": "CSE 2102", "sec": "A", "teacher": "JR", "room": "OS Lab"},
        {"time": "8.50 am", "sub": "CSE 2102", "sec": "A", "teacher": "JR", "room": "OS Lab"},
        {"time": "9.40 am", "sub": "CSE 2102", "sec": "A", "teacher": "JR", "room": "OS Lab"},
        {"time": "10.50 am", "sub": "CSE 2101", "sec": "A", "teacher": "JR", "room": "103"},
        {"time": "12.30 pm", "sub": "CSE 2101", "sec": "B", "teacher": "AYS", "room": "203"},
         {"time": "2.30 pm", "sub": "CSE 2102", "sec": "B", "teacher": "AYS", "room": "PG Lab"},
         {"time": "3.20 pm", "sub": "CSE 2102", "sec": "B", "teacher": "AYS", "room": "PG Lab"},
         {"time": "4.10 pm", "sub": "CSE 2102", "sec": "B", "teacher": "AYS", "room": "PG Lab"},
         {"time": "2.30 pm", "sub": "CSE 2104", "sec": "B", "teacher": "MZI", "room": "HW Lab"},
         {"time": "3.20 pm", "sub": "CSE 2104", "sec": "B", "teacher": "MZI", "room": "HW Lab"},
         {"time": "4.10 pm", "sub": "CSE 2104", "sec": "B", "teacher": "MZI", "room": "HW Lab"},
        {"time": "10.50 am", "sub": "CSE 2103", "sec": "C", "teacher": "MZI", "room": "203"},
        {"time": "11.40 am", "sub": "CSE 2103", "sec": "C", "teacher": "MZI", "room": "203"},
      ],
        "1st Year Odd Sem": [
        {"time": "9.40 am", "sub": "CSE 1101", "sec": "B", "teacher": "SeN", "room": "101"},
        {"time": "2.30 pm", "sub": "CSE 1102", "sec": "C", "teacher": "SeN", "room": "ACL"},
         {"time": "3.20 pm", "sub": "CSE 1102", "sec": "C", "teacher": "SeN", "room": "ACL"},
          {"time": "4.10 pm", "sub": "CSE 1102", "sec": "C", "teacher": "SeN", "room": "ACL"},
            {"time": "2.30 pm", "sub": "CSE 1102", "sec": "C", "teacher": "NIM", "room": "ACL"},
         {"time": "3.20 pm", "sub": "CSE 1102", "sec": "C", "teacher": "NIM", "room": "ACL"},
          {"time": "4.10 pm", "sub": "CSE 1102", "sec": "C", "teacher": "NIM", "room": "ACL"},
      ],
    },


    "Sunday": {
      "4th Year Even Sem": [
        {"time": "8.00 am", "sub": "CSE 4207", "sec": "A", "teacher": "NS", "room": "201"},
        {"time": "8.50 am", "sub": "CSE 4203", "sec": "A", "teacher": "RT", "room": "201"},
        {"time": "9.40 am", "sub": "CSE 4201", "sec": "A", "teacher": "SA", "room": "201"},
        {"time": "10.50 am", "sub": "CSE 4207", "sec": "B", "teacher": "FAR", "room": "201"},
        {"time": "11.40 am", "sub": "CSE 4215", "sec": "B", "teacher": "MAN", "room": "201"},
        {"time": "12.30 pm", "sub": "CSE 4203", "sec": "B", "teacher": "MIT", "room": "201"},
        {"time": "2.30 pm", "sub": "CSE 4204", "sec": "B", "teacher": "MRI", "room": "HPCl"},
        {"time": "3.20 pm", "sub": "CSE 4204", "sec": "B", "teacher": "MRI", "room": "HPCl"},
        {"time": "4.10 pm", "sub": "CSE 4204", "sec": "B", "teacher": "MRI", "room": "HPCl"},
        {"time": "10.50 am", "sub": "CSE 4203", "sec": "C", "teacher": "MIT", "room": "202"},
        {"time": "11.40 am", "sub": "CSE 4207", "sec": "C", "teacher": "FAR", "room": "202"},
        {"time": "12.30 pm", "sub": "CSE 4211", "sec": "C", "teacher": "AMR", "room": "202"},
      ],
        "3rd Year Even Sem": [
        {"time": "2.30 pm", "sub": "CSE 3205", "sec": "A", "teacher": "EKH", "room": "101"},
        {"time": "3.20 pm", "sub": "CSE 3203", "sec": "A", "teacher": "SA", "room": "101"},
        {"time": "4.10 pm", "sub": "CSE 3201", "sec": "A", "teacher": "FAR", "room": "101"},
        {"time": "8.00 am", "sub": "CSE 3208", "sec": "B", "teacher": "MAN", "room": "NW Lab"},
        {"time": "8.50 am", "sub": "CSE 3208", "sec": "B", "teacher": "MAN", "room": "NW Lab"},
        {"time": "9.40 am", "sub": "CSE 3208", "sec": "B", "teacher": "MAN", "room": "NW Lab"},
        {"time": "10.50 am", "sub": "CSE 3207", "sec": "B", "teacher": "MAN", "room": "203"},
        {"time": "11.40 am", "sub": "CSE 3205", "sec": "B", "teacher": "FP", "room": "203"},
        {"time": "12.30 pm", "sub": "CSE 3201", "sec": "B", "teacher": "FAR", "room": "203"},
        {"time": "8.50 am", "sub": "CSE 3201", "sec": "C", "teacher": "NS", "room": "202"},
        {"time": "9.40 am", "sub": "CSE 3207", "sec": "C", "teacher": "NOS", "room": "202"},
        {"time": "2.30 pm", "sub": "CSE 3205", "sec": "C", "teacher": "FP", "room": "102"},
        {"time": "3.20 pm", "sub": "CSE 3205", "sec": "C", "teacher": "HsN", "room": "102"},
        {"time": "4.10 pm", "sub": "CSE 3205", "sec": "C", "teacher": "HsN", "room": "102"},


      ],
        "3rd Year Odd Sem": [
        {"time": "8.00 am", "sub": "CSE 3102", "sec": "A", "teacher": "AYS", "room": "PG Lab"},
        {"time": "8.50 am", "sub": "CSE 3102", "sec": "A", "teacher": "AYS", "room": "PG Lab"},
        {"time": "9.40 am", "sub": "CSE 3102", "sec": "A", "teacher": "AYS", "room": "PG Lab"},
        {"time": "2.30 pm", "sub": "CSE 3109", "sec": "A", "teacher": "MAN", "room": "103"},
        {"time": "3.20 pm", "sub": "CSE 3107", "sec": "A", "teacher": "FP", "room": "103"},
        {"time": "10.50 am", "sub": "CSE 3103", "sec": "B", "teacher": "MSH", "room": "102"},
        {"time": "11.40 am", "sub": "CSE 3105", "sec": "B", "teacher": "NS", "room": "102"},
        {"time": "12.30 pm", "sub": "CSE 3101", "sec": "B", "teacher": "AYS", "room": "102"},
        {"time": "10.50 am", "sub": "CSE 3105", "sec": "C", "teacher": "NOS", "room": "103"},
        {"time": "11.40 am", "sub": "CSE 3103", "sec": "C", "teacher": "MIT", "room": "103"},
        {"time": "12.30 pm", "sub": "CSE 3107", "sec": "C", "teacher": "FP", "room": "101"},
      ],
          "2nd Year Odd Sem": [
        {"time": "8.50 am", "sub": "CSE 2103", "sec": "A", "teacher": "BA", "room": "203"},
        {"time": "9.40 am", "sub": "CSE 2103", "sec": "A", "teacher": "BA", "room": "203"},
        {"time": "10.50 am", "sub": "CSE 2101", "sec": "A", "teacher": "JR", "room": "101"},
        {"time": "11.40 am", "sub": "CSE 2101", "sec": "A", "teacher": "JR", "room": "101"},
        {"time": "8.00 am", "sub": "CSE 2102", "sec": "B", "teacher": "JR", "room": "ACL"},
        {"time": "8.50 am", "sub": "CSE 2102", "sec": "B", "teacher": "JR", "room": "ACL"},
        {"time": "9.40 am", "sub": "CSE 2102", "sec": "B", "teacher": "JR", "room": "ACL"},
        {"time": "8.00 am", "sub": "CSE 2104", "sec": "B", "teacher": "MZI", "room": "HW Lab"},
        {"time": "8.50 am", "sub": "CSE 2104", "sec": "B", "teacher": "MZI", "room": "HW Lab"},
        {"time": "9.40 am", "sub": "CSE 2104", "sec": "B", "teacher": "MZI", "room": "HW Lab"},
        {"time": "10.50 am", "sub": "CSE 2104", "sec": "C", "teacher": "BA", "room": "HW Lab"},
        {"time": "11.40 am", "sub": "CSE 2104", "sec": "C", "teacher": "BA", "room": "HW Lab"},
        {"time": "12.30 pm", "sub": "CSE 2104", "sec": "C", "teacher": "BA", "room": "HW Lab"},
        {"time": "2.30 pm", "sub": "CSE 2102", "sec": "C", "teacher": "AYS", "room": "NW Lab"},
        {"time": "3.20 pm", "sub": "CSE 2102", "sec": "C", "teacher": "AYS", "room": "NW Lab"},
        {"time": "4.10 pm", "sub": "CSE 2102", "sec": "C", "teacher": "AYS", "room": "NW Lab"},
      ],
          "1st Year Odd Sem": [
        {"time": "10.50 am", "sub": "CSE 1102", "sec": "B", "teacher": "SeN", "room": "PG Lab"},
        {"time": "11.40 am", "sub": "CSE 1102", "sec": "B", "teacher": "SeN", "room": "PG Lab"},
        {"time": "12.30 pm", "sub": "CSE 1102", "sec": "B", "teacher": "SeN", "room": "PG Lab"},
        {"time": "8.50 am", "sub": "CSE 1101", "sec": "C", "teacher": "NIM", "room": "101"},
        {"time": "9.40 am", "sub": "CSE 1101", "sec": "C", "teacher": "NIM", "room": "101"},
      ],
    },

       "Monday": {
      "4th Year Even Sem": [
        {"time": "10.50 am", "sub": "CSE 4215", "sec": "A", "teacher": "SUZ", "room": "101"},
        {"time": "11.40 am", "sub": "CSE 4221", "sec": "A", "teacher": "JR", "room": "101"},
        {"time": "12.30 pm", "sub": "CSE 4203", "sec": "A", "teacher": "RT", "room": "101"},
        {"time": "8.50 am", "sub": "CSE 4221", "sec": "B", "teacher": "JR", "room": "201"},
        {"time": "9.40 am", "sub": "CSE 4221", "sec": "B", "teacher": "JR", "room": "201"},
        {"time": "10.50 am", "sub": "CSE 4215", "sec": "B", "teacher": "MAN", "room": "203"},
        {"time": "8.00 am", "sub": "CSE 4202", "sec": "C", "teacher": "SA", "room": "ACL"},
        {"time": "8.50 am", "sub": "CSE 4202", "sec": "C", "teacher": "SA", "room": "ACL"},
        {"time": "9.40 am", "sub": "CSE 4202", "sec": "C", "teacher": "SA", "room": "ACL"},
        {"time": "10.50 am", "sub": "CSE 4221", "sec": "C", "teacher": "AMR", "room": "102"},
        {"time": "11.40 am", "sub": "CSE 4215", "sec": "C", "teacher": "SUZ", "room": "102"},
        {"time": "12.30 pm", "sub": "CSE 4215", "sec": "C", "teacher": "SUZ", "room": "102"},
      ],
        "3rd Year Even Sem": [
        {"time": "10.50 am", "sub": "CSE 3203", "sec": "A", "teacher": "SA", "room": "103"},
        {"time": "11.40 am", "sub": "CSE 3203", "sec": "A", "teacher": "SA", "room": "103"},
        {"time": "12.30 pm", "sub": "CSE 3205", "sec": "A", "teacher": "EKH", "room": "103"},
        {"time": "2.30 pm", "sub": "CSE 3207", "sec": "B", "teacher": "MAN", "room": "201"},
        {"time": "3.20 pm", "sub": "CSE 3203", "sec": "B", "teacher": "HsN", "room": "201"},
        {"time": "4.10 pm", "sub": "CSE 3203", "sec": "B", "teacher": "HsN", "room": "201"},
        {"time": "8.00 am", "sub": "CSE 3201", "sec": "C", "teacher": "NS", "room": "203"},
        {"time": "8.50 am", "sub": "CSE 3209", "sec": "C", "teacher": "MFF", "room": "203"},
        {"time": "9.40 am", "sub": "CSE 3207", "sec": "C", "teacher": "NOS", "room": "203"},
        {"time": "10.50 am", "sub": "CSE 3202", "sec": "C", "teacher": "NS", "room": "ACL"},
        {"time": "11.40 am", "sub": "CSE 3202", "sec": "C", "teacher": "NS", "room": "ACL"},
        {"time": "12.30 pm", "sub": "CSE 3202", "sec": "C", "teacher": "NS", "room": "ACL"},
        {"time": "10.50 am", "sub": "CSE 3210", "sec": "C", "teacher": "MFF", "room": "HPCL"},
        {"time": "11.40 am", "sub": "CSE 3210", "sec": "C", "teacher": "MFF", "room": "HPCL"},
        {"time": "12.30 pm", "sub": "CSE 3210", "sec": "C", "teacher": "MFF", "room": "HPCL"},
      ],
        "3rd Year Odd Sem": [
        {"time": "8.00 am", "sub": "CSE 3108", "sec": "A", "teacher": "FP", "room": "OS Lab"},
        {"time": "8.50 am", "sub": "CSE 3108", "sec": "A", "teacher": "FP", "room": "OS Lab"},
        {"time": "9.40 am", "sub": "CSE 3108", "sec": "A", "teacher": "FP", "room": "OS Lab"},
        {"time": "10.50 am", "sub": "CSE 3107", "sec": "A", "teacher": "FP", "room": "202"},
        {"time": "11.40 am", "sub": "CSE 3105", "sec": "A", "teacher": "NOS", "room": "202"},
        {"time": "12.30 pm", "sub": "CSE 3103", "sec": "A", "teacher": "MSH", "room": "202"},
        {"time": "2.30 pm", "sub": "CSE 3106", "sec": "A", "teacher": "NS", "room": "NW Lab"},
        {"time": "3.20 pm", "sub": "CSE 3106", "sec": "A", "teacher": "NS", "room": "NW Lab"},
        {"time": "4.10 pm", "sub": "CSE 3106", "sec": "A", "teacher": "NS", "room": "NW Lab"},
        {"time": "8.00 am", "sub": "CSE 3102", "sec": "B", "teacher": "AYS", "room": "PG Lab"},
        {"time": "8.50 am", "sub": "CSE 3102", "sec": "B", "teacher": "AYS", "room": "PG Lab"},
        {"time": "9.40 am", "sub": "CSE 3102", "sec": "B", "teacher": "AYS", "room": "PG Lab"},
        {"time": "10.50 am", "sub": "CSE 3107", "sec": "B", "teacher": "UD", "room": "201"},
        {"time": "11.40 am", "sub": "CSE 3103", "sec": "B", "teacher": "MSH", "room": "201"},
        {"time": "12.30 pm", "sub": "CSE 3109", "sec": "B", "teacher": "AMR", "room": "201"},
        {"time": "8.00 am", "sub": "CSE 3103", "sec": "C", "teacher": "MIT", "room": "101"},
        {"time": "8.50 am", "sub": "CSE 3109", "sec": "C", "teacher": "AMR", "room": "101"},
        {"time": "11.40 am", "sub": "CSE 3107", "sec": "C", "teacher": "FP", "room": "203"},
      ],
        "2nd Year Odd Sem": [
        {"time": "9.40 am", "sub": "CSE 2103", "sec": "A", "teacher": "BA", "room": "101"},
        {"time": "10.50 am", "sub": "CSE 2104", "sec": "A", "teacher": "BA", "room": "HW Lab"},
        {"time": "11.40 am", "sub": "CSE 2104", "sec": "A", "teacher": "BA", "room": "HW Lab"},
        {"time": "12.30 pm", "sub": "CSE 2104", "sec": "A", "teacher": "BA", "room": "HW Lab"},
        {"time": "10.50 am", "sub": "CSE 2102", "sec": "A", "teacher": "JR", "room": "SW Lab"},
        {"time": "11.40 am", "sub": "CSE 2102", "sec": "A", "teacher": "JR", "room": "SW Lab"},
        {"time": "12.30 pm", "sub": "CSE 2102", "sec": "A", "teacher": "JR", "room": "SW Lab"},
        {"time": "8.00 am", "sub": "CSE 2103", "sec": "B", "teacher": "MZI", "room": "202"},
        {"time": "4.10 pm", "sub": "CSE 2101", "sec": "C", "teacher": "AYS", "room": "103"},
      ],
        "1st Year Odd Sem": [
        {"time": "9.40 am", "sub": "CSE 1101", "sec": "A", "teacher": "NIM", "room": "103"},
        {"time": "10.50 am", "sub": "CSE 1102", "sec": "A", "teacher": "NIM", "room": "OS Lab"},
        {"time": "11.40 am", "sub": "CSE 1102", "sec": "A", "teacher": "NIM", "room": "OS Lab"},
        {"time": "12.30 pm", "sub": "CSE 1102", "sec": "A", "teacher": "NIM", "room": "OS Lab"},
        {"time": "10.50 am", "sub": "CSE 1102", "sec": "B", "teacher": "SeN", "room": "PG Lab"},
        {"time": "11.40 am", "sub": "CSE 1102", "sec": "B", "teacher": "SeN", "room": "PG Lab"},
        {"time": "12.30 pm", "sub": "CSE 1102", "sec": "B", "teacher": "SeN", "room": "PG Lab"},
        {"time": "2.30 pm", "sub": "CSE 1101", "sec": "B", "teacher": "SeN", "room": "102"},
        {"time": "2.30 pm", "sub": "CSE 1100", "sec": "C", "teacher": "MIT", "room": "101"},
        {"time": "3.20 pm", "sub": "CSE 1100", "sec": "C", "teacher": "MIT", "room": "101"},
        {"time": "4.10 pm", "sub": "CSE 1100", "sec": "C", "teacher": "MIT", "room": "101"},

      ],
    },

           "Tuesday": {
      "4th Year Even Sem": [
        {"time": "10.50 am", "sub": "CSE 4221", "sec": "A", "teacher": "JR", "room": "101"},
        {"time": "11.40 am", "sub": "CSE 4215", "sec": "A", "teacher": "SUZ", "room": "101"},
        {"time": "12.30 pm", "sub": "CSE 4215", "sec": "A", "teacher": "SUZ", "room": "101"},
        {"time": "8.00 am", "sub": "CSE 4201", "sec": "B", "teacher": "MSH", "room": "102"},
        {"time": "8.50 am", "sub": "CSE 4203", "sec": "B", "teacher": "MIT", "room": "102"},
        {"time": "9.40 am", "sub": "CSE 4221", "sec": "B", "teacher": "JR", "room": "102"},
        {"time": "8.00 am", "sub": "CSE 4207", "sec": "C", "teacher": "FAR", "room": "202"},
        {"time": "8.50 am", "sub": "CSE 4221", "sec": "C", "teacher": "AMR", "room": "202"},
        {"time": "9.40 am", "sub": "CSE 4215", "sec": "C", "teacher": "SUZ", "room": "202"},
        {"time": "10.50 am", "sub": "CSE 4204", "sec": "C", "teacher": "MIT", "room": "HPCL"},
        {"time": "11.40 am", "sub": "CSE 4204", "sec": "C", "teacher": "MIT", "room": "HPCL"},
        {"time": "12.30 pm", "sub": "CSE 4204", "sec": "C", "teacher": "MIT", "room": "HPCL"},
      ],
         "3rd Year Even Sem": [
        {"time": "10.50 am", "sub": "CSE 3207", "sec": "A", "teacher": "MAN", "room": "102"},
        {"time": "11.40 am", "sub": "CSE 3201", "sec": "A", "teacher": "FAR", "room": "102"},
        {"time": "12.30 pm", "sub": "CSE 3209", "sec": "A", "teacher": "MFF", "room": "102"},
        {"time": "2.30 pm", "sub": "CSE 3204", "sec": "A", "teacher": "SA", "room": "HW Lab"},
        {"time": "3.20 pm", "sub": "CSE 3204", "sec": "A", "teacher": "SA", "room": "HW Lab"},
        {"time": "4.10 pm", "sub": "CSE 3204", "sec": "A", "teacher": "SA", "room": "HW Lab"},
        {"time": "2.30 pm", "sub": "CSE 3206", "sec": "A", "teacher": "EKH", "room": "OS Lab"},
        {"time": "3.20 pm", "sub": "CSE 3206", "sec": "A", "teacher": "EKH", "room": "OS Lab"},
        {"time": "4.10 pm", "sub": "CSE 3206", "sec": "A", "teacher": "EKH", "room": "OS Lab"},
        {"time": "8.00 am", "sub": "CSE 3207", "sec": "B", "teacher": "MAN", "room": "203"},
        {"time": "8.50 am", "sub": "CSE 3201", "sec": "B", "teacher": "FAR", "room": "203"},
        {"time": "9.40 am", "sub": "CSE 3209", "sec": "B", "teacher": "MIT", "room": "203"},
        {"time": "10.50 am", "sub": "CSE 3204", "sec": "B", "teacher": "HsN", "room": "HW Lab"},
        {"time": "11.40 am", "sub": "CSE 3204", "sec": "B", "teacher": "HsN", "room": "HW Lab"},
        {"time": "12.30 pm", "sub": "CSE 3204", "sec": "B", "teacher": "HsN", "room": "HW Lab"},
        {"time": "2.30 pm", "sub": "CSE 3210", "sec": "B", "teacher": "MIT", "room": "HPCL"},
        {"time": "3.20 pm", "sub": "CSE 3210", "sec": "B", "teacher": "MIT", "room": "HPCL"},
        {"time": "4.10 pm", "sub": "CSE 3210", "sec": "B", "teacher": "MIT", "room": "HPCL"},
        {"time": "8.00 am", "sub": "CSE 3207", "sec": "C", "teacher": "NOS", "room": "101"},
        {"time": "8.50 am", "sub": "CSE 3205", "sec": "C", "teacher": "FP", "room": "101"},
        {"time": "9.40 am", "sub": "CSE 3203", "sec": "C", "teacher": "SA", "room": "101"},
        {"time": "10.50 am", "sub": "CSE 3206", "sec": "C", "teacher": "FP", "room": "NW Lab"},
        {"time": "11.40 am", "sub": "CSE 3206", "sec": "C", "teacher": "FP", "room": "NW Lab"},
        {"time": "12.30 pm", "sub": "CSE 3206", "sec": "C", "teacher": "FP", "room": "NW Lab"},
      ],
         "3rd Year Odd Sem": [
        {"time": "10.50 am", "sub": "CSE 3105", "sec": "A", "teacher": "NOS", "room": "103"},
        {"time": "11.40 am", "sub": "CSE 3109", "sec": "A", "teacher": "MAN", "room": "103"},
        {"time": "12.30 pm", "sub": "CSE 3101", "sec": "A", "teacher": "AYS", "room": "103"},
        {"time": "8.50 am", "sub": "CSE 3107", "sec": "B", "teacher": "UD", "room": "201"},
        {"time": "9.40 am", "sub": "CSE 3105", "sec": "B", "teacher": "NS", "room": "201"},
        {"time": "10.50 am", "sub": "CSE 3101", "sec": "B", "teacher": "AYS", "room": "201"},
        {"time": "12.30 pm", "sub": "CSE 3103", "sec": "B", "teacher": "MSH", "room": "201"},
        {"time": "2.30 pm", "sub": "CSE 3106", "sec": "B", "teacher": "NS", "room": "NW Lab"},
        {"time": "3.20 pm", "sub": "CSE 3106", "sec": "B", "teacher": "NS", "room": "NW Lab"},
        {"time": "4.10 pm", "sub": "CSE 3106", "sec": "B", "teacher": "NS", "room": "NW Lab"},
        {"time": "11.40 am", "sub": "CSE 3105", "sec": "C", "teacher": "NOS", "room": "202"},
        {"time": "12.30 pm", "sub": "CSE 3101", "sec": "C", "teacher": "SeN", "room": "103"},
        {"time": "2.30 pm", "sub": "CSE 3108", "sec": "C", "teacher": "UD", "room": "OS Lab"},
        {"time": "3.20 pm", "sub": "CSE 3108", "sec": "C", "teacher": "UD", "room": "OS Lab"},
        {"time": "4.10 pm", "sub": "CSE 3108", "sec": "C", "teacher": "UD", "room": "OS Lab"},
      ],
         "2nd Year Odd Sem": [
        {"time": "3.20 pm", "sub": "CSE 2101", "sec": "B", "teacher": "JR", "room": "202"},
        {"time": "4.10 pm", "sub": "CSE 2103", "sec": "B", "teacher": "MZI", "room": "202"},
        {"time": "8.00 am", "sub": "CSE 2104", "sec": "C", "teacher": "MZI", "room": "HW Lab"},
        {"time": "8.50 am", "sub": "CSE 2104", "sec": "C", "teacher": "MZI", "room": "HW Lab"},
        {"time": "9.40 am", "sub": "CSE 2104", "sec": "C", "teacher": "MZI", "room": "HW Lab"},
        {"time": "8.00 am", "sub": "CSE 2102", "sec": "C", "teacher": "AYS", "room": "PG Lab"},
        {"time": "8.50 am", "sub": "CSE 2102", "sec": "C", "teacher": "AYS", "room": "PG Lab"},
        {"time": "9.40 am", "sub": "CSE 2102", "sec": "C", "teacher": "AYS", "room": "PG Lab"},
        {"time": "10.50 am", "sub": "CSE 2103", "sec": "C", "teacher": "MZI", "room": "203"},
        {"time": "11.40 am", "sub": "CSE 2101", "sec": "C", "teacher": "AYS", "room": "203"},
      ],
         "1st Year Odd Sem": [
        {"time": "8.50 am", "sub": "CSE 1101", "sec": "B", "teacher": "SeN", "room": "104"},
        {"time": "2.30 pm", "sub": "CSE 1100", "sec": "B", "teacher": "MSH", "room": "101"},
        {"time": "3.20 pm", "sub": "CSE 1100", "sec": "B", "teacher": "MSH", "room": "101"},
        {"time": "4.10 pm", "sub": "CSE 1100", "sec": "B", "teacher": "MSH", "room": "101"},
        {"time": "9.40 am", "sub": "CSE 1101", "sec": "C", "teacher": "NIM", "room": "103"},
        {"time": "10.50 am", "sub": "CSE 1102", "sec": "C", "teacher": "NIM", "room": "PG Lab"},
        {"time": "11.40 am", "sub": "CSE 1102", "sec": "C", "teacher": "NIM", "room": "PG Lab"},
        {"time": "12.30 pm", "sub": "CSE 1102", "sec": "C", "teacher": "NIM", "room": "PG Lab"},
      ],
    },
           "Wednesday": {
      "4th Year Even Sem": [
        {"time": "8.00 am", "sub": "CSE 4201", "sec": "A", "teacher": "SA", "room": "101"},
        {"time": "8.50 am", "sub": "CSE 4221", "sec": "A", "teacher": "JR", "room": "101"},
        {"time": "9.40 am", "sub": "CSE 4207", "sec": "A", "teacher": "NS", "room": "101"},
        {"time": "2.30 pm", "sub": "CSE 4202", "sec": "A", "teacher": "SA", "room": "HPCL"},
        {"time": "3.20 pm", "sub": "CSE 4202", "sec": "A", "teacher": "SA", "room": "HPCL"},
        {"time": "4.10 pm", "sub": "CSE 4202", "sec": "A", "teacher": "SA", "room": "HPCL"},
        {"time": "10.50 am", "sub": "CSE 4215", "sec": "B", "teacher": "MAN", "room": "101"},
        {"time": "11.40 am", "sub": "CSE 4201", "sec": "B", "teacher": "MSH", "room": "101"},
        {"time": "12.30 pm", "sub": "CSE 4207", "sec": "B", "teacher": "FAR", "room": "101"},
        {"time": "8.00 am", "sub": "CSE 4207", "sec": "C", "teacher": "FAR", "room": "201"},
        {"time": "8.50 am", "sub": "CSE 4203", "sec": "C", "teacher": "MIT", "room": "201"},
        {"time": "9.40 am", "sub": "CSE 4201", "sec": "C", "teacher": "MSH", "room": "201"},
      ],
       "3rd Year Even Sem": [
        {"time": "8.00 am", "sub": "CSE 3210", "sec": "A", "teacher": "MFF", "room": "HPCL"},
        {"time": "8.50 am", "sub": "CSE 3210", "sec": "A", "teacher": "MFF", "room": "HPCL"},
        {"time": "9.40 am", "sub": "CSE 3210", "sec": "A", "teacher": "MFF", "room": "HPCL"},
        {"time": "8.00 am", "sub": "CSE 3208", "sec": "A", "teacher": "MAN", "room": "PG Lab"},
        {"time": "8.50 am", "sub": "CSE 3208", "sec": "A", "teacher": "MAN", "room": "PG Lab"},
        {"time": "9.40 am", "sub": "CSE 3208", "sec": "A", "teacher": "MAN", "room": "PG Lab"},
        {"time": "10.50 am", "sub": "CSE 3209", "sec": "A", "teacher": "MFF", "room": "201"},
        {"time": "11.40 am", "sub": "CSE 3201", "sec": "A", "teacher": "FAR", "room": "201"},
        {"time": "12.30 pm", "sub": "CSE 3207", "sec": "A", "teacher": "MAN", "room": "201"},
        {"time": "2.30 pm", "sub": "CSE 3202", "sec": "A", "teacher": "FAR", "room": "OS Lab"},
        {"time": "3.20 pm", "sub": "CSE 3202", "sec": "A", "teacher": "FAR", "room": "OS Lab"},
        {"time": "4.10 pm", "sub": "CSE 3202", "sec": "A", "teacher": "FAR", "room": "OS Lab"},
        {"time": "10.50 am", "sub": "CSE 3201", "sec": "B", "teacher": "FAR", "room": "202"},
        {"time": "11.40 am", "sub": "CSE 3209", "sec": "B", "teacher": "MIT", "room": "202"},
        {"time": "12.30 pm", "sub": "CSE 3205", "sec": "B", "teacher": "FP", "room": "202"},
        {"time": "10.50 am", "sub": "CSE 3204", "sec": "C", "teacher": "SA", "room": "HW Lab"},
        {"time": "11.40 am", "sub": "CSE 3204", "sec": "C", "teacher": "SA", "room": "HW Lab"},
        {"time": "12.30 pm", "sub": "CSE 3204", "sec": "C", "teacher": "SA", "room": "HW Lab"},
        {"time": "2.30 pm", "sub": "CSE 3209", "sec": "C", "teacher": "MFF", "room": "201"},
        {"time": "3.20 pm", "sub": "CSE 3205", "sec": "C", "teacher": "FP", "room": "201"},
      ],
       "3rd Year Odd Sem": [
        {"time": "10.50 am", "sub": "CSE 3102", "sec": "A", "teacher": "AYS", "room": "SW Lab"},
        {"time": "11.40 am", "sub": "CSE 3102", "sec": "A", "teacher": "AYS", "room": "SW Lab"},
        {"time": "12.30 pm", "sub": "CSE 3102", "sec": "A", "teacher": "AYS", "room": "SW Lab"},
        {"time": "2.30 pm", "sub": "CSE 3107", "sec": "A", "teacher": "FP", "room": "103"},
        {"time": "3.20 pm", "sub": "CSE 3103", "sec": "A", "teacher": "MSH", "room": "103"},
        {"time": "4.10 pm", "sub": "CSE 3103", "sec": "A", "teacher": "MSH", "room": "103"},
        {"time": "8.50 am", "sub": "CSE 3101", "sec": "B", "teacher": "SeN", "room": "203"},
        {"time": "9.40 am", "sub": "CSE 3101", "sec": "B", "teacher": "AMR", "room": "203"},
        {"time": "10.50 am", "sub": "CSE 3102", "sec": "B", "teacher": "SeN", "room": "PG Lab"},
        {"time": "11.40 am", "sub": "CSE 3102", "sec": "B", "teacher": "SeN", "room": "PG Lab"},
        {"time": "12.30 pm", "sub": "CSE 3102", "sec": "B", "teacher": "SeN", "room": "PG Lab"},
        {"time": "2.30 pm", "sub": "CSE 3108", "sec": "B", "teacher": "UD", "room": "SW Lab"},
        {"time": "3.20 pm", "sub": "CSE 3108", "sec": "B", "teacher": "UD", "room": "SW Lab"},
        {"time": "4.10 pm", "sub": "CSE 3108", "sec": "B", "teacher": "UD", "room": "SW Lab"},
        {"time": "8.00 am", "sub": "CSE 3106", "sec": "C", "teacher": "NOS", "room": "NW Lab"},
        {"time": "8.50 am", "sub": "CSE 3106", "sec": "C", "teacher": "NOS", "room": "NW Lab"},
        {"time": "9.40 am", "sub": "CSE 3106", "sec": "C", "teacher": "NOS", "room": "NW Lab"},
        {"time": "10.50 am", "sub": "CSE 3103", "sec": "C", "teacher": "MIT", "room": "104"},
        {"time": "11.40 am", "sub": "CSE 3109", "sec": "C", "teacher": "AMR", "room": "104"},
        {"time": "12.30 pm", "sub": "CSE 3109", "sec": "C", "teacher": "AMR", "room": "104"},
        {"time": "2.30 pm", "sub": "CSE 3102", "sec": "C", "teacher": "SeN", "room": "PG Lab"},
        {"time": "3.20 pm", "sub": "CSE 3102", "sec": "C", "teacher": "SeN", "room": "PG Lab"},
        {"time": "4.10 pm", "sub": "CSE 3102", "sec": "C", "teacher": "SeN", "room": "PG Lab"},
      ],
       "2nd Year Odd Sem": [
        {"time": "8.50 am", "sub": "CSE 2103", "sec": "B", "teacher": "MZI", "room": "103"},
        {"time": "9.40 am", "sub": "CSE 2101", "sec": "B", "teacher": "JR", "room": "103"},
        {"time": "3.20 pm", "sub": "CSE 2101", "sec": "C", "teacher": "AYS", "room": "202"},
      ],
       "1st Year Odd Sem": [
        {"time": "8.50 am", "sub": "CSE 1101", "sec": "A", "teacher": "NIM", "room": "102"},
        {"time": "9.40 am", "sub": "CSE 1101", "sec": "A", "teacher": "NIM", "room": "102"},
        {"time": "10.50 am", "sub": "CSE 1102", "sec": "A", "teacher": "NIM", "room": "NW Lab"},
        {"time": "11.40 am", "sub": "CSE 1102", "sec": "A", "teacher": "NIM", "room": "NW Lab"},
        {"time": "12.30 pm", "sub": "CSE 1102", "sec": "A", "teacher": "NIM", "room": "NW Lab"},
        {"time": "2.30 pm", "sub": "CSE 1100", "sec": "A", "teacher": "EKH", "room": "101"},
        {"time": "3.20 pm", "sub": "CSE 1100", "sec": "A", "teacher": "EKH", "room": "101"},
        {"time": "4.10 pm", "sub": "CSE 1100", "sec": "A", "teacher": "EKH", "room": "101"},
      ],
    },
  };

  static List<Map<String, String>> searchTeacher(String teacherShortName) {
    List<Map<String, String>> results = [];

    schedule.forEach((day, yearData) {
      yearData.forEach((year, classes) {
        for (var classInfo in classes) {
          if (classInfo["teacher"]!.contains(teacherShortName)) {
            results.add({
              "day": day,
              "time": classInfo["time"]!,
              "sub": classInfo["sub"]!,
              "year": year,
              "sec": classInfo["sec"]!,
              "room": classInfo["room"]!,
            });
          }
        }
      });
    });

    return results;
  }
}
